on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.18.2

  generate-terraform-docs:
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/generate-terraform-docs.yml@v0.18.2
    with:
      output-file: README.md
      # This artifact is referenced by the cog.toml
      artifact-name: terraform-docs

  lint-pipeline:
    uses: armakuni/github-actions/.github/workflows/lint-pipeline.yml@v0.18.2

  run-tests:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/run-tests.yml
    secrets:
      aws-account-id: ${{ secrets.ARMAKUNI_AWS_PROD_ACCOUNT_ID }}

  create-release:
    needs:
      - check-conventional-commits
      - generate-terraform-docs
      - lint-pipeline
      - run-tests
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.18.2
    secrets: inherit
    with:
      download-artifacts: true

